server_name: 211.55.6 
network_name: elk_network 

nginx_image: nginx:1.15-alpine
nginx_hostname: nginx01
nginx_conf_dir: /usr/share/nginx

elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
elasticsearch_hostname: elasticsearch01 
elasticsearch_conf_dir: /usr/share/elasticsearch

kibana_image: docker.elastic.co/kibana/kibana:7.4.2
kibana_hostname: kibana01

logstash_image: docker.elastic.co/logstash/logstash:7.4.2
logstash_hostname: logstash01
logstash_conf_dir: /usr/share/logstash

certbot_image: certbot/certbot
certbot_hostname: certbot01
certbot_conf_dir: /usr/share/certbot
certbot_email: info@example.com

elastic_password: "kibana"
kibana_password: "kibana"
